app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import Integer, String, Boolean, DateTime
from . import db, login_manager


class User(UserMixin, db.Model):
    """
    Represents a user in the system.

    Attributes:
        id (int): The unique identifier for the user.
        username (str): The username of the user.
        email (str): The email address of the user.
        password_hash (str): The hashed password of the user.
        is_active (bool): Indicates whether the user is active or not.
        last_login (DateTime): The date and time of the user's last login (optional).
    """

    __tablename__ = "users"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    username: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    email: Mapped[str] = mapped_column(String(120), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(128))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    last_login: Mapped[DateTime] = mapped_column(DateTime, nullable=True)

    # Relationships
    activities: Mapped[list["Activity"]] = relationship(
        "Activity", back_populates="user"
    )

    def set_password(self, password: str) -> None:
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        return check_password_hash(self.password_hash, password)

    def __repr__(self) -> str:
        return f"<User {self.username}>"


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


class Activity(db.Model):
    """
    Represents an activity in the system.

    Attributes:
        id (int): The unique identifier for the activity.
        description (str): The description of the activity.
        type (str): The type of the activity.
        participants (int): The number of participants for the activity.
        user_id (int): The ID of the user who saved the activity.
    """

    __tablename__ = "activities"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    description: Mapped[str] = mapped_column(String(256))
    type: Mapped[str] = mapped_column(String(64))
    participants: Mapped[int] = mapped_column(Integer)
    user_id: Mapped[int] = mapped_column(Integer, db.ForeignKey("users.id"))

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="activities")

    def __repr__(self) -> str:
        return f"<Activity {self.description}>"

app/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    PasswordField,
    BooleanField,
    SubmitField,
    SelectField,
    IntegerField,
)
from wtforms.validators import DataRequired, Email, EqualTo


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')]
    )
    submit = SubmitField('Register')


class FilterForm(FlaskForm):
    type = SelectField(
        'Type',
        choices=[
            ('', 'All'),
            ('recreational', 'Recreational'),
            ('social', 'Social'),
            ('diy', 'DIY'),
            ('education', 'Education'),
            ('charity', 'Charity'),
            ('cooking', 'Cooking'),
            ('relaxation', 'Relaxation'),
            ('music', 'Music'),
            ('busywork', 'Busywork'),
        ],
    )
    participants = IntegerField('Participants', default=1)
    submit = SubmitField('Get Activity')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, upgrade
from flask_login import LoginManager
from flask_bootstrap import Bootstrap5
from flask_wtf.csrf import CSRFProtect

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
bootstrap = Bootstrap5()
csrf = CSRFProtect()


def create_app():
    app = Flask(__name__)
    app.config.from_object('config.Config')

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    csrf.init_app(app)

    with app.app_context():
        from . import routes
        app.register_blueprint(routes.main_bp)

        db.create_all()

        upgrade()  # Automatically apply migrations at startup

        return app

app/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_user, logout_user, login_required
from datetime import datetime, UTC
from . import db
from .models import User, Activity
from .forms import LoginForm, RegistrationForm, FilterForm
from .utils import fetch_random_activity

main_bp = Blueprint('main', __name__)


@main_bp.route('/', methods=['GET', 'POST'])
@main_bp.route('/index', methods=['GET', 'POST'])
def index():
    form = FilterForm()
    if form.validate_on_submit():
        try:
            result = fetch_random_activity(form.type.data, form.participants.data)
            activity = result['activity']
            if 'error' in activity:
                return jsonify({'error': activity['error']})
            image_url = result['image_url']
            return jsonify({'activity': activity, 'image_url': image_url})
        except Exception as e:
            return jsonify({'error': str(e)})
    return render_template('home.html', title='Home', form=form)


@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid email or password')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        user.last_login = datetime.now(UTC)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('login.html', title='Sign In', form=form)


@main_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@main_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        password = form.password.data
        password2 = form.password2.data
        if password != password2:
            flash("Passwords do not match")
            return redirect(url_for("main.register"))
        user.set_password(form.password.data)
        user.last_login = None  # Set last_login to None during registration
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)


@main_bp.route('/favorites')
@login_required
def favorites():
    user = User.query.get(current_user.id)
    activities = user.activities  # Directly use the list of activities
    return render_template('favorites.html', title='Favorites', activities=activities)


@main_bp.route('/save_activity', methods=['POST'])
@login_required
def save_activity():
    data = request.json
    if not data:
        return jsonify(status='error', message='Invalid request format'), 400
    try:
        activity = Activity(
            description=data['description'],
            type=data['type'],
            participants=data['participants'],
            user_id=current_user.id,
        )
        db.session.add(activity)
        db.session.commit()
        return jsonify(status='success')
    except Exception as e:
        return jsonify(status='error', message=str(e)), 400


@main_bp.route('/remove_activity', methods=['POST'])
@login_required
def remove_activity():
    data = request.json
    activity = Activity.query.get(data['id'])
    if activity and activity.user_id == current_user.id:
        db.session.delete(activity)
        db.session.commit()
        return jsonify(status='success')
    return jsonify(status='error')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		<!-- Title -->
		<title>{% block title %}Boredom Buster{% endblock %}</title>
		<!-- Bootstrap CSS -->
		{{ bootstrap.load_css() }}
		<!-- Bootstrap Icons -->
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
		/>
		<!-- Custom CSS -->
		{% block css %}{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="{{ url_for('main.index') }}"
					>Boredom Buster</a
				>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarNav"
					aria-controls="navbarNav"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.index') }}"><i class="bi bi-house"></i> Home</a>
						</li>
						{% if current_user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.favorites') }}"
								><i class="bi bi-heart"></i> Favorites</a
							>
						</li>
						{% endif %}
					</ul>
					<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
						{% if current_user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.logout') }}"><i class="bi bi-box-arrow-in-left"></i> Logout</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.login') }}"><i class="bi bi-box-arrow-in-right"></i> Login</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.register') }}"
								><i class="bi bi-person-plus"></i> Register</a
							>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
		<div class="container my-4">{% block content %}{% endblock %}</div>
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<!-- Bootstrap core JS-->
		{{ bootstrap.load_js() }}
		<!-- Custom JS -->
		{% block scripts %}{% endblock %}
	</body>
</html>

app/templates/favorites.html
<!-- extends from base -->
{% extends "base.html" %}
<!-- Title -->
{% block title %}Favorites{% endblock %}
<!-- Content -->
{% block content %}
<div class="container mt-5">
	<h1 class="text-center mb-4">Your Favorite Activities</h1>
	{% if activities %}
	<div class="row row-cols-1 row-cols-md-2 g-4">
		{% for activity in activities %}
		<div class="col">
			<div class="card h-100 shadow-sm">
				<div class="card-body d-flex flex-column justify-content-between">
					<div>
						<h5 class="card-title">{{ activity.description }}</h5>
						<span class="badge bg-primary me-2">
							<i class="bi bi-activity"></i> {{ activity.type | capitalize}}
						</span>
						<span class="badge bg-secondary">
							<i class="bi bi-people-fill"></i> {{ activity.participants }}
							Participants
						</span>
					</div>
					<button
						class="btn btn-danger mt-3 align-self-end remove-activity"
						data-id="{{ activity.id }}"
					>
						<i class="bi bi-trash"></i> Remove
					</button>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
	{% else %}
	<div class="alert alert-warning text-center">
		<p>You have no saved favorite activities.</p>
	</div>
	{% endif %}
</div>
{% endblock %}
<!-- Scripts -->
{% block scripts %}
<script>
	$(document).ready(function () {
		$('.remove-activity').on('click', function () {
			var activityId = $(this).data('id');
			$.ajax({
				url: '{{ url_for("main.remove_activity") }}',
				type: 'POST',
				contentType: 'application/json',
				data: JSON.stringify({ id: activityId }),
				headers: {
					'X-CSRFToken': '{{ csrf_token() }}', // Include the CSRF token as a header
				},
				success: function (response) {
					if (response.status === 'success') {
						location.reload();
					} else {
						alert('Error removing activity');
					}
				},
			});
		});
	});
</script>
{% endblock %}

app/templates/home.html
<!-- extends from base -->
{% extends "base.html" %}
<!-- Title -->
{% block title %}Home{% endblock %}
<!-- Content -->
{% block content %}
<div class="container mt-5">
	<h1 class="text-center mb-4">Boredom Buster</h1>
	<form
		id="filter-form"
		method="post"
		class="row g-3 justify-content-center mb-5"
	>
		{{ form.hidden_tag() }}
		<div class="col-md-4">
			{{ form.type.label(class="form-label") }} {{
			form.type(class_="form-control shadow-sm") }}
		</div>
		<div class="col-md-4">
			{{ form.participants.label(class="form-label") }} {{
			form.participants(class_="form-control shadow-sm") }}
		</div>
		<div class="col-md-2 d-grid">
			<button type="submit" class="btn btn-primary mt-4 shadow-sm">
				<i class="bi bi-search"></i> {{ form.submit.label.text }}
			</button>
		</div>
	</form>

	<h2 id="activity-title" class="mb-4" style="display: none">
		Suggested Activity
	</h2>
	<div
		id="activity-container"
		class="card mb-5 shadow-sm"
		style="display: none"
	>
		<div class="row g-0 h-100">
			<div class="col-md-4 d-flex align-items-center">
				<img
					src="https://via.placeholder.com/450x300.png?text=Activity+Image"
					class="img-fluid rounded-start"
					alt="Activity Image"
					id="activity-image"
				/>
			</div>
			<div class="col-md-8 d-flex flex-column justify-content-center">
				<div
					class="card-body d-flex flex-column align-items-center justify-content-center"
				>
					<h3 class="card-title" id="activity-description"></h3>
					<div class="mb-2">
						<span class="badge bg-primary"
							><i class="bi bi-activity"></i>
							<span id="activity-type-badge"></span
						></span>
						<span class="badge bg-secondary"
							><i class="bi bi-people-fill"></i>
							<span id="activity-participants-badge"></span
						></span>
					</div>
				</div>
				{% if current_user.is_authenticated %}
				<div class="text-end p-3 mt-auto">
					<button id="save-activity" class="btn btn-success shadow-sm">
						<i class="bi bi-floppy"></i> Save Activity
					</button>
				</div>
				{% endif %}
			</div>
		</div>
	</div>

	<div
		id="error-container"
		class="alert alert-danger shadow-sm"
		style="display: none"
	>
		<h4 class="alert-heading">No Activity Found</h4>
		<p>
			Sorry, we couldn't find any activity with the specified parameters. Please
			try different options.
		</p>
	</div>
</div>
{% endblock %}
<!-- Scripts -->
{% block scripts %}
<script>
	$(document).ready(function() {
	    $('#filter-form').on('submit', function(event) {
	        event.preventDefault();
	        var formData = $(this).serialize();
	        $.ajax({
	            url: '{{ url_for('main.index') }}',
	            type: 'POST',
	            data: formData,
	            success: function(response) {
	                if (response.activity) {
	                    $('#activity-title').fadeIn();
	                    $('#activity-container').fadeIn();
	                    $('#error-container').hide();
	                    $('#activity-description').text(response.activity.activity);
	                    $('#activity-type-badge').text(response.activity.type.charAt(0).toUpperCase() + response.activity.type.slice(1));
	                    $('#activity-participants-badge').text(response.activity.participants + ' Participants');
	                    $('#save-activity').data('activity', response.activity);

	                    if (response.image_url) {
							$('#activity-image').attr('src', response.image_url).show();
						} else {
							$('#activity-image').hide();
						};
	                } else {
	                    $('#activity-title').hide();
	                    $('#activity-container').hide();
	                    $('#error-container').fadeIn();
	                }
	            },
	            error: function() {
	                $('#activity-title').hide();
	                $('#activity-container').hide();
	                $('#error-container').fadeIn();
	            }
	        });
	    });

	    $('#save-activity').on('click', function() {
	        var activity = $(this).data('activity');
	        $.ajax({
	            url: '{{ url_for('main.save_activity') }}',
	            type: 'POST',
	            contentType: 'application/json',
	            data: JSON.stringify({
	                description: activity.activity,
	                type: activity.type,
	                participants: activity.participants
	            }),
	            headers: {
	                'X-CSRFToken': "{{ csrf_token() }}"
	            },
	            success: function(response) {
	                alert('Activity saved successfully!');
	            },
	            error: function(response) {
	                alert('Error saving activity: ' + response.statusText);
	            }
	        });
	    });
	});
</script>
{% endblock %}

app/templates/login.html
<!-- extends from base -->
{% extends "base.html" %}
<!-- Title -->
{% block title %}Login{% endblock %}
<!-- Content -->
{% block content %}
<div class="container mt-5">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<div class="card shadow-sm">
				<div class="card-body">
					<h2 class="text-center mb-4">
						<i class="bi bi-box-arrow-in-left"></i> Login
					</h2>
					<form method="POST" action="{{ url_for('main.login') }}">
						{{ form.hidden_tag() }} {% for error in form.email.errors %}
						<div class="alert alert-danger">{{ error }}</div>
						{% endfor %}
						<div class="input-group mb-3">
							<span class="input-group-text"
								><i class="bi bi-envelope"></i
							></span>
							<div class="form-floating">
								{{ form.email(class_="form-control", placeholder="Email") }} {{
								form.email.label(class="form-label") }}
							</div>
						</div>

						{% for error in form.password.errors %}
						<div class="alert alert-danger">{{ error }}</div>
						{% endfor %}
						<div class="input-group mb-3">
							<span class="input-group-text"><i class="bi bi-lock"></i></span>
							<div class="form-floating">
								{{ form.password(class_="form-control", placeholder="Password")
								}} {{ form.password.label(class="form-label") }}
							</div>
						</div>

						<div class="form-check mb-3">
							{{ form.remember_me(class_="form-check-input") }} {{
							form.remember_me.label(class="form-check-label") }}
						</div>

						<div class="d-grid">
							{{ form.submit(class_="btn btn-primary btn-lg shadow-sm") }}
						</div>
					</form>
					<p class="mt-3 text-center">
						Don't have an account?
						<a href="{{ url_for('main.register') }}">Register here</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/register.html
<!-- extends from base -->
{% extends "base.html" %}
<!-- Title -->
{% block title %}Register{% endblock %}
<!-- Content -->
{% block content %}
<div class="container mt-5">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<div class="card shadow-sm">
				<div class="card-body">
					<h2 class="text-center mb-4">
						<i class="bi bi-person-plus"></i> Register
					</h2>
					<form method="POST" action="{{ url_for('main.register') }}">
						{{ form.hidden_tag() }} {% for error in form.username.errors %}
						<div class="alert alert-danger">{{ error }}</div>
						{% endfor %}
						<div class="input-group mb-3">
							<span class="input-group-text"><i class="bi bi-person"></i></span>
							<div class="form-floating">
								{{ form.username(class_="form-control", placeholder="Username")
								}} {{ form.username.label(class="form-label") }}
							</div>
						</div>

						{% for error in form.email.errors %}
						<div class="alert alert-danger">{{ error }}</div>
						{% endfor %}
						<div class="input-group mb-3">
							<span class="input-group-text"
								><i class="bi bi-envelope"></i
							></span>
							<div class="form-floating">
								{{ form.email(class_="form-control", placeholder="Email") }} {{
								form.email.label(class="form-label") }}
							</div>
						</div>

						{% for error in form.password.errors %}
						<div class="alert alert-danger">{{ error }}</div>
						{% endfor %}
						<div class="input-group mb-3">
							<span class="input-group-text"><i class="bi bi-lock"></i></span>
							<div class="form-floating">
								{{ form.password(class_="form-control", placeholder="Password")
								}} {{ form.password.label(class="form-label") }}
							</div>
						</div>

						{% for error in form.password2.errors %}
						<div class="alert alert-danger">{{ error }}</div>
						{% endfor %}
						<div class="input-group mb-3">
							<span class="input-group-text"><i class="bi bi-lock"></i></span>
							<div class="form-floating">
								{{ form.password2(class_="form-control", placeholder="Confirm
								Password") }} {{ form.password2.label(class="form-label") }}
							</div>
						</div>

						<div class="d-grid">
							{{ form.submit(class_="btn btn-primary btn-lg shadow-sm") }}
						</div>
					</form>
					<p class="mt-3 text-center">
						Already have an account?
						<a href="{{ url_for('main.login') }}">Login here</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}